#ifndef THREEDSONG_VERSION_H
#define THREEDSONG_VERSION_H

#define THREEDSONG_NAME        "3DSong"
#define THREEDSONG_VERSION     "0.5"
#define THREEDSONG_VERSION_MAJOR 0
#define THREEDSONG_VERSION_MINOR 5
#define THREEDSONG_VERSION_PATCH 0
#define THREEDSONG_TITLE       "3DSong 0.5"

#endif
